(test
 (name ocaml_tests)
 (modules ocaml_tests)
 (libraries actuator_engine actuator_binding alcotest ctypes-foreign)
 (link_flags (-cclib -Wl,--export-dynamic)))

(test
 (name integration_test)
 (modules integration_test)
 (libraries actuator_engine actuator_binding alcotest ctypes-foreign)
 (link_flags (-cclib -Wl,--export-dynamic)))

(test
 (name fuser_test)
 (modules fuser_test)
 (libraries actuator_engine alcotest))

(test
 (name logger_test)
 (modules logger_test)
 (libraries actuator_engine alcotest))

(test
 (name error_test)
 (modules error_test)
 (libraries actuator_engine alcotest str))

(test
 (name time_util_test)
 (modules time_util_test)
 (libraries actuator_engine alcotest))
